---
galaxy_info:
  author: Gilberto Ficara <g.ficara@stardata.it>
  description: Disables SELinux on next reboot and sets it in permissive mode until then
  company: Stardata S.r.l. - http://www.stardata.it
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  categories:
  - system
dependencies: []

