- name: install firewalld ...
  dnf:
    name: firewalld
    state: latest

  become: yes

- name: ensure that firewalld is started and enable at boot
  service: name=firewalld enabled=yes state=started
  become: yes

- name: Allow http/https
  command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https
  become: yes

- name: Open the required ports
  command: firewall-cmd --zone=public --permanent --add-port="{{ item }}"/tcp

  with_items:
    - 50090
    - 50105
    - 50075
    - 50070
    - 50475
    - 50470
    - 8032
    - 8030
    - 8088
    - 8090
    - 8031
    - 8033
    - 4040  
    - 9000
  become: yes

- name: Reloading firewalld to apply the changes ...
  command: firewall-cmd --reload
  become: yes
