- name: Clearing HDFS logs, temporal files and old data on masters ...
  script: /etc/ansible/roles/ansible-clean-HADOOP-processes/scripts/clear-hdfs-masters.sh
  when: inventory_hostname in groups['masters']
  become: yes

- name: Clearing HDFS logs, temporal files and old data on slaves ...
  script: /etc/ansible/roles/ansible-clean-HADOOP-processes/scripts/clear-hdfs-slaves.sh
  when: inventory_hostname in groups['storage']
  become: yes
