# -------------------------------- Installing Spark ------------------------------------------ #

# Note:  We do not need to donwload the spark package from internet, we have our own already downloaded.
- name: Extracting Spark package

  unarchive:
    src: "{{ spark_package_file }}"
    dest: "{{ download_folder }}"
  when: inventory_hostname in groups['webservers']

- name: "Changing the spark folder name from {{ spark_folder_path_name_old }} to {{ download_folder }}/{{ spark_folder_name_new }}"

  command: "mv {{ spark_folder_path_name_old }} {{ download_folder }}/{{ spark_folder_name_new }}"
  when: inventory_hostname in groups['webservers']


