# Define file path
- name: Set remote file path here
  set_fact: remote_file_path=/etc/hosts

# Create a blank file
- name: Create a new file
  file: path="{{ remote_file_path }}" state=touch
  become: yes
# Check remote file
- stat: path="{{ remote_file_path }}"
  register: file_path

# Writing content
- lineinfile:
    path: "{{ remote_file_path }}"
    line: "{{ item }}"
  with_items: "{{ hosts }}"
  become: yes
