---
#- hosts: ssh-authority
#  become: yes
#  roles:
#    - ansible-authorized-keys

#- hosts: webservers
#  become: yes
#  roles:
#    - ansible-configure-hosts-file
#    - ansible-configure-firewall
#    - ansible-disable-selinux
#    - ansible-install-java

- hosts: masters:slaves:storage
  become: yes        
  roles:
#    - ansible-configure-install-Hadoop
    - ansible-clean-HADOOP-processes

#- hosts: masters:processing
#  roles:
#    - ansible-install-Spark
#    - ansible-install-Scala
