---
- hosts: webservers
  become: yes
  roles:
#    - ansible-configure-hosts-file
#    - ansible-configure-firewall
#    - ansible-disable-selinux
#    - ansible-install-java
    - ansible-configure-install-Hadoop
#    - ansible-install-Spark
#    - ansible-install-Scala
